# Generated by Django 3.2 on 2024-06-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_favoriteproduct_productaddon_productaddonoption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productaddonoption',
            old_name='Price',
            new_name='price',
        ),
    ]
