# Generated by Django 3.2 on 2024-06-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_store_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
