# Generated by Django 3.2 on 2024-06-20 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vender', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vender',
            name='close_at',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='vender',
            name='open_at',
            field=models.TimeField(null=True),
        ),
    ]
