# Generated by Django 3.2 on 2024-06-21 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vender', '0002_auto_20240620_1717'),
        ('category', '0003_alter_category_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_by', models.CharField(blank=True, max_length=50, null=True)),
                ('name', models.CharField(max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, null=True)),
                ('image', models.ImageField(null=True, upload_to='home_banners/')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('vender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='vender.vender')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
